import openai
import os

# Make sure you replace "Your_OpenAI_API_Key" with your actual OpenAI API key, or better,
# use environment variables for added security.
# For example, in your terminal:
# export OPENAI_API_KEY='your_api_key_here'
# And in this script, use:
# openai.api_key = os.getenv("OPENAI_API_KEY")
#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

openai.api_key = os.getenv("OPENAI_API_KEY", "Your_OpenAI_API_Key")


def send_prompt_to_openai(prompt, engine="text-davinci-003", max_tokens=150, temperature=0.7):
    """
    Sends a prompt to the specified OpenAI model and gets the generated text as output.

    Parameters:
    - prompt (str): The prompt to send to the model.
    - engine (str, optional): The ID of the model to use. Defaults to "text-davinci-003".
    - max_tokens (int, optional): The maximum number of tokens to generate. Defaults to 150.
    - temperature (float, optional): Controls the randomness of the response. Defaults to 0.7.
    
    Returns:
    - str: The text generated by the model.
    """
    try:
        response = openai.Completion.create(
            engine=engine,
            prompt=prompt,
            max_tokens=max_tokens,
            temperature=temperature
        )
        generated_text = response.choices[0].text.strip()
        return generated_text
    except Exception as e:
        print(f"An error occurred: {e}")
        return ""

# Example prompt
prompt = """The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.
Human: Hello, who are you?
AI: I am an AI created by OpenAI. How can I assist you today?
Human:"""

# Sending the prompt to the OpenAI API
response_text = send_prompt_to_openai(prompt)

print("Response from OpenAI:", response_text)